import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@workspace/ui/globals.css"
import { AuthProvider } from "@workspace/ui/providers/AuthProvider";
import { AlertProvider } from "@workspace/ui/providers/AlertModalProvider";
import Header from "@workspace/ui/components/layout/header";
import { Separator } from "@workspace/ui/components/separator";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-[100vh] flex flex-col`}
      >
        <AuthProvider>
          <AlertProvider>
            <Header />
            <Separator />
            <div className="container mx-auto md:w-[60%] px-4">
              {children}
            </div>
          </AlertProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
